/** High-quality Unsplash images (auto format, cropped, compressed) */
const u = (photoId: string, width = 1200) =>
  `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=${width}&q=80`;

export const IMAGES = {
  hero: {
    home: u('photo-1522202176988-66273c2fd55f', 1400),
    slideAi: '/images/hero/slide-ai.png',
    slideDev: '/images/hero/slide-dev.png',
    slideCloud: '/images/hero/slide-cloud.png',
    courses: '/images/hero/courses-hero.png',
    about: '/images/about/about-hero.png',
    contact: '/images/hero/contact-hero.png',
    resources: '/images/hero/resources-hero.png',
    enroll: u('photo-1434030216411-0b793f4b4173', 1400),
    bonus: u('photo-1504639725590-34d0984388bd', 1400),
  },
  heroCaptions: {
    courses: 'Structured programs with real-world projects',
    about: 'The future of practical, career-ready learning',
    contact: 'Real people. Real support — we’re here to help',
    resources: 'Free roadmaps, guides & curated content',
    enroll: 'Start your application in minutes',
    bonus: 'Certifications & career extras included',
  },
  brand: {
    logo: '/zyvotrix-logo.png',
  },
  /** Human + tech visuals for program landing pages */
  programVisuals: {
    aac: {
      hero: '/images/programs/aac-hero.png',
      learning: '/images/programs/aac-learning.png',
      labs: '/images/programs/aac-labs.png',
      liveSessions: '/images/programs/aac-live-sessions.png',
      buildProjects: '/images/programs/aac-build-projects.png',
      aiStack: '/images/programs/aac-ai-stack.png',
      audience: '/images/programs/aac-audience.png',
      career: '/images/programs/aac-career.png',
      certificate: '/images/programs/aac-certificate.png',
      learner: '/images/hero/slide-ai.png',
      mentor: '/images/programs/aac-mentor.png',
      projects: '/images/features/projects.png',
      classroom: '/images/features/curriculum.png',
    },
    dop: {
      hero: '/images/programs/dop-hero.png',
      learning: '/images/programs/dop-learning.png',
      mentor: '/images/programs/dop-mentor.png',
      labs: '/images/programs/dop-labs.png',
      liveSessions: '/images/programs/dop-live-sessions.png',
      buildProjects: '/images/programs/dop-build-projects.png',
      devopsStack: '/images/programs/dop-devops-stack.png',
      audience: '/images/programs/dop-audience.png',
      career: '/images/programs/dop-career.png',
      certificate: '/images/programs/dop-certificate.png',
      learner: '/images/hero/slide-dev.png',
      projects: '/images/features/projects.png',
      classroom: '/images/features/curriculum.png',
    },
    aws: {
      hero: '/images/programs/aws-hero.png',
      learning: '/images/programs/aws-learning.png',
      mentor: '/images/programs/aws-mentor.png',
      labs: '/images/programs/aws-labs.png',
      liveSessions: '/images/programs/aws-live-sessions.png',
      buildProjects: '/images/programs/aws-build-projects.png',
      cloudStack: '/images/programs/aws-cloud-stack.png',
      audience: '/images/programs/aws-audience.png',
      career: '/images/programs/aws-career.png',
      certificate: '/images/programs/aws-certificate.png',
    },
    ds: {
      hero: '/images/programs/ds-hero.png',
      learning: '/images/programs/ds-learning.png',
      mentor: '/images/programs/ds-mentor.png',
      labs: '/images/programs/ds-labs.png',
      liveSessions: '/images/programs/ds-live-sessions.png',
      buildProjects: '/images/programs/ds-build-projects.png',
      dataStack: '/images/programs/ds-data-stack.png',
      audience: '/images/programs/ds-audience.png',
      career: '/images/programs/ds-career.png',
      certificate: '/images/programs/ds-certificate.png',
    },
  },
  programs: {
    dop: '/images/programs/dop.png',
    aac: '/images/programs/aac.png',
    aws: '/images/programs/aws.png',
    dataScience: '/images/programs/data-science.png',
    /** @deprecated legacy aliases — use dop/aac/aws/dataScience */
    webDev: '/images/programs/data-science.png',
    devops: '/images/programs/dop.png',
    cloud: '/images/programs/aws.png',
    ai: '/images/programs/aac.png',
    analytics: '/images/programs/data-science.png',
    agentic: '/images/programs/aac.png',
    security: '/images/programs/dop.png',
  },
  /** About page — 5 strategic visuals + founder photo */
  aboutVisuals: {
    hero: '/images/about/about-hero.png',
    story: '/images/about/about-story.png',
    mission: '/images/about/about-mission.png',
    vision: '/images/about/about-vision.png',
    cta: '/images/about/about-cta.png',
    founder: '/images/about/founder.png',
  },
  team: u('photo-1522071820081-009f0129c71c', 800),
  instructor: u('photo-1507003211169-0a1dd7228f2d', 800),
  classroom: u('photo-1523240795612-9a054b0db644', 800),
  workshop: u('photo-1531482615713-2afd69097998', 800),
  certification: u('photo-1434030216411-0b793f4b4173', 600),
  learning: u('photo-1516321497487-e288fb19713f', 800),
  notFound: u('photo-1451187580459-43490279c0fa', 1000),
} as const;
